### PR TITLE
Removed reliance on specific g++ version

### PR DESCRIPTION
**Pull request by milescsmith**
Removing the '-8' fixed the compilation error:

    CMake Error at CMakeLists.txt:3 (PROJECT):
    The CMAKE_CXX_COMPILER:

      g++-8

    is not a full path and was not found in the PATH.

### CODE REVIEW

**Comment by cciccole** [comment]
Does multiprocessing definitely still work correctly on your system after this change? It doesn't on mine.

On my OSX system, g++ maps to the version that either ships with the computer or installs with Xcode tools at usr/bin/g++ (I'm not 100% sure of origination). That version doesn't support the OpenMP needs of this package.

I thought it was simplest to be specific and have something I knew worked with multiprocessing on at least OSX. I wrote a brief note about this in the readme:

> Note that there is an edit to the CMakeLists.txt file that was made for compatibility with Mac OSX. Other environments may require backing this edit out or otherwise augmenting this file.

That edit is adding the first two lines ([see diff here](https://github.com/omiq-ai/Multicore-opt-SNE/commit/aacee5a3cdd6e78357c482ec0fb72f44378726ce#diff-47d42e84969289099005fe4bb24cf0cf)).

**Comment by milescsmith** [comment]
Shoot, I feel like an idiot for totally missing that that was a fix for OSX.  I've changed CMakeList so that it checks the platform before compilation and tested that it works on both OSX and Linux.

**Comment by cciccole** [comment]
No prob, and thanks! Looks good. Only problem is the introduction of the string formatting changes breaks functionality on Python 2.7. I think the days of having to accommodate that are numbered but no sense in breaking it just for string formatting.

**Comment by cciccole** [comment]
Thanks!

**Pull request merged**
